# Generated by Django 3.2.21 on 2023-10-15 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Abia Umuahia', 'Abia Umuahia'), ('Adamawa Yola', 'Adamawa Yola'), ('Akwa Ibom Uyo', 'Akwa Ibom Uyo'), ('Anambra Awka', 'Anambra Awka'), ('Bauchi Bauchi', 'Bauchi Bauchi'), ('Bayelsa Yenagoa', 'Bayelsa Yenagoa'), ('Benue Makurdi', 'Benue Makurdi'), ('Borno Maiduguri', 'Borno Maiduguri'), ('Cross River Calabar', 'Cross River Calabar'), ('Delta Asaba', 'Delta Asaba'), ('Ebonyi Abakaliki', 'Ebonyi Abakaliki'), ('Edo Benin City', 'Edo Benin City'), ('Ekiti Ado-Ekiti', 'Ekiti Ado-Ekiti'), ('Enugu Enugu', 'Enugu Enugu'), ('Gombe Gombe', 'Gombe Gombe'), ('Imo Owerri', 'Imo Owerri'), ('Jigawa Dutse', 'Jigawa Dutse'), ('Kaduna Kaduna', 'Kaduna Kaduna'), ('Kano Kano', 'Kano Kano'), ('Katsina Katsina', 'Katsina Katsina'), ('Kebbi Birnin Kebbi', 'Kebbi Birnin Kebbi'), ('Kogi Lokoja', 'Kogi Lokoja'), ('Kwara Ilorin', 'Kwara Ilorin'), ('Lagos Ikeja', 'Lagos Ikeja'), ('Nasarawa Lafia', 'Nasarawa Lafia'), ('Niger Minna', 'Niger Minna'), ('Ogun Abeokuta', 'Ogun Abeokuta'), ('Ondo Akure', 'Ondo Akure'), ('Osun Osogbo', 'Osun Osogbo'), ('Oyo Ibadan', 'Oyo Ibadan'), ('Plateau Jos', 'Plateau Jos'), ('Rivers Port Harcourt', 'Rivers Port Harcourt'), ('Sokoto Sokoto', 'Sokoto Sokoto'), ('Taraba Jalingo', 'Taraba Jalingo'), ('Yobe Damaturu', 'Yobe Damaturu'), ('Zamfara Gusau', 'Zamfara Gusau'), ('Federal Capital Territory Abuja', 'Federal Capital Territory Abuja')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
